//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fixture02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public int CheckID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string Code { get; set; }
        public Nullable<int> SeqID { get; set; }
        public string Name { get; set; }
        public string FamilyID { get; set; }
        public string FamilyName { get; set; }
        public string Model { get; set; }
        public string PartNo { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string AddUserID { get; set; }
        public string AddUserName { get; set; }
        public string CheckUserName { get; set; }
        public string CheckType { get; set; }
        public string CheckState { get; set; }
        public string CheckResult1 { get; set; }
        public string CheckResult2 { get; set; }
        public string CheckResult3 { get; set; }
        public string CheckResult4 { get; set; }
        public string CheckResult5 { get; set; }
        public string CheckResult6 { get; set; }
        public string CheckResult7 { get; set; }
        public string CheckResult8 { get; set; }
        public string Problem { get; set; }
        public string WorkcellID { get; set; }
        public string Pic { get; set; }
    }
}
