//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fixture02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inout
    {
        public int IinOutID { get; set; }
        public int ItemID { get; set; }
        public string ViaUserName { get; set; }
        public string State { get; set; }
        public string LineID { get; set; }
        public string LineName { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Model { get; set; }
        public string PartNo { get; set; }
        public string FamilyID { get; set; }
        public string FamilyName { get; set; }
        public System.DateTime AddDate { get; set; }
        public string AddUserID { get; set; }
        public string AddUserName { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string ReviewUserID { get; set; }
        public string ReviewUserName { get; set; }
    }
}
