//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fixture02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jig()
        {
            this.Jigitem = new HashSet<Jigitem>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public string FamilyID { get; set; }
        public string FamilyName { get; set; }
        public string Model { get; set; }
        public string PartNo { get; set; }
        public string WorkcellID { get; set; }
        public string WorkcellName { get; set; }
        public string UsedFor { get; set; }
        public Nullable<int> UPL { get; set; }
        public string OwnerID { get; set; }
        public string OwnerName { get; set; }
        public Nullable<int> PMPeriod { get; set; }
        public System.DateTime AddDate { get; set; }
        public string AddUserID { get; set; }
        public string AddUserName { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string EditUserID { get; set; }
        public string EditUserName { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jigitem> Jigitem { get; set; }
    }
}
