//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fixture02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jigitem
    {
        public int ItemID { get; set; }
        public string Code { get; set; }
        public int SeqID { get; set; }
        public string BillNo { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<int> UsedCount { get; set; }
        public string Location { get; set; }
        public string State { get; set; }
        public string Pic { get; set; }
        public System.DateTime AddDate { get; set; }
        public string AddUserID { get; set; }
        public string AddUserName { get; set; }
        public Nullable<System.DateTime> FirstReviewDate { get; set; }
        public string FirstReviewUserID { get; set; }
        public string FirstReviewUserName { get; set; }
        public Nullable<System.DateTime> SecondReviewDate { get; set; }
        public string SecondReviewUserID { get; set; }
        public string SecondReviewUserName { get; set; }
        public Nullable<System.DateTime> WaitTime { get; set; }
        public string BackNote { get; set; }
    
        public virtual Jig Jig { get; set; }
    }
}
