//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fixture02.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fixtureEntities : DbContext
    {
        public fixtureEntities()
            : base("name=fixtureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Workcell> Workcell { get; set; }
        public virtual DbSet<Family> Family { get; set; }
        public virtual DbSet<Jig> Jig { get; set; }
        public virtual DbSet<Jigitem> Jigitem { get; set; }
        public virtual DbSet<Inout> Inout { get; set; }
        public virtual DbSet<Line> Line { get; set; }
        public virtual DbSet<repair> repair { get; set; }
    }
}
